# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98a487807b5b5e38a9eccfeb7971abde02156ca6e20e6c2f52c3169a34090e386f89dad3365d2fd67e10f1a7c3489131f48bf9b17cf95c8011415a3f25ebef06

test:
  secret_key_base: 6463fc1357c18e7778dba0941b13e72c6ee931384494efaa303d324a173de206c7541fca699e495225280f53c029e4bb5937cafa9699dbe58023956feaae25e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
